---

# Create temporary SSH keys for the setup.

- include: playbooks/create_key_pair.yml


# Security groups for one and all!

- include: playbooks/create_security_groups.yml


# Build and configure.

- include: playbooks/create_instance_generic.yml
#- include: playbooks/provision_instance_generic.yml


# Post-deployment tasks for all instances.

# Adds predefined key to SSH authorized keys to all instances (all_instances hostgroup)
# Destroys temporary deployment EC2 key pair
- include: playbooks/destroy_key_pair.yml

