---

- hosts: localhost
  connection: local
  gather_facts: False

  vars_files:
    - ../config/config.yml

  tasks:

    - name: Create common security group for generic servers
      ec2_group:
        name: "{{ prefix }}-generic"
        description: Allow HTTP & SSH in and all out
        region: "{{ ec2_region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0

